"""Per-brief markdown cards for the workbook."""

from __future__ import annotations

from pathlib import Path

from sejeroe.align import align_article
from sejeroe.baseline import baselines_for, comparison_table
from sejeroe.fixtures import ARTICLES
from sejeroe.models import Article
from sejeroe.paths import GENERATED_DOCS, ensure_output_dirs
from sejeroe.stylebook import grade_roles


def _card_dir() -> Path:
    ensure_output_dirs()
    target = GENERATED_DOCS / "cards"
    target.mkdir(parents=True, exist_ok=True)
    return target


def render_card(article: Article) -> str:
    table = comparison_table(article)
    roles = grade_roles(article)
    silver_gates = roles["silver_da"]
    lead1_gates = roles["lead1_da"]
    alignment = align_article(article)
    quote = article.quotes[0]
    lines = [
        f"# {article.id} — {article.headline_da}",
        "",
        f"Split: `{article.split}`",
        "",
        "## Slot card",
        "",
        f"- WHO: {article.slots.who}",
        f"- WHAT: {article.slots.what}",
        f"- WHEN: {article.slots.when}",
        f"- WHERE: {article.slots.where}",
        f"- WHY: {article.slots.why}",
        f"- HOW: {article.slots.how}",
        f"- Figures: {', '.join(article.figures) or '—'}",
        "",
        "## Quote",
        "",
        f"- Speaker: {quote.speaker}",
        f"- DA: {quote.danish}",
        f"- EN: {quote.english}",
        "",
        "## Hops",
        "",
        f"**Manchet (DA):** {article.lead_da}",
        "",
        f"**Silver DA:** {article.summary_da}",
        "",
        f"**Oracle DA:** {article.oracle_da}",
        "",
        "## Extractive vs silver",
        "",
        f"- lead1 manchet {table['lead1_manchet']} vs silver {table['silver_manchet']}"
        f" (lead1 beats silver: {table['lead1_beats_silver_manchet']})",
        f"- lead1 slots {table['lead1_slots']} vs silver {table['silver_slots']}"
        f" (lead1 beats silver: {table['lead1_beats_silver_slots']})",
        f"- R1 vs oracle: lead1 {table['lead1_r1_oracle']} / silver {table['silver_r1_oracle']}",
        "",
        "## Stylebook (silver)",
        "",
    ]
    for gate in silver_gates.gates:
        mark = "pass" if gate.passed else "FAIL"
        lines.append(f"- `{gate.name}`: {mark} — {gate.detail}")
    lines.extend(
        [
            "",
            f"Silver gates {silver_gates.passed}/{silver_gates.total}; "
            f"lead1 gates {lead1_gates.passed}/{lead1_gates.total}.",
            "",
            "## Parallel sentences",
            "",
        ]
    )
    for pair in alignment.pairs:
        flag = " (quote)" if pair.is_quote else ""
        lines.append(
            f"{pair.index}. DA {pair.da_words}w / EN {pair.en_words}w "
            f"(x{pair.word_ratio:.2f}){flag}"
        )
        lines.append(f"   - {pair.danish}")
        lines.append(f"   - {pair.english}")
    if not alignment.aligned:
        lines.append("")
        lines.append(f"Leftover DA: {list(alignment.leftover_da)}")
        lines.append(f"Leftover EN: {list(alignment.leftover_en)}")
    lines.append("")
    return "\n".join(lines)


def write_cards() -> dict[str, Path]:
    target = _card_dir()
    written: dict[str, Path] = {}
    index = ["# Sejerø article cards", "", "Generated by `python3 -m sejeroe cards`.", ""]
    for article in ARTICLES:
        path = target / f"{article.id}.md"
        path.write_text(render_card(article), encoding="utf-8")
        written[article.id] = path
        index.append(f"- [{article.id} — {article.headline_da}]({article.id}.md)")
    index_path = target / "README.md"
    index_path.write_text("\n".join(index) + "\n", encoding="utf-8")
    written["index"] = index_path
    return written
