"""Self-contained HTML almanac for the measure ledger."""

from __future__ import annotations

from html import escape
from pathlib import Path

from .corpus import ARTICLES
from .hops import HopPair
from .ledger import CorpusLedger, build_corpus_ledger
from .nllb_scar import demo_cases
from .paths import REPORT_DIR
from .world import PARISH

OK_LABELS = {"ok"}


def render_html(ledger: CorpusLedger | None = None) -> str:
    ledger = ledger or build_corpus_ledger(ARTICLES)
    rows = []
    for article, entry in zip(ARTICLES, ledger.articles):
        rows.append(_article_section(article, entry))
    scar_rows = "".join(
        f"<tr><td>{escape(case.name)}</td><td>{escape(' '.join(case.hypothesis))}</td>"
        f"<td>{escape(' '.join(case.decoded))}</td>"
        f"<td>{'harmless' if case.harmless else 'drops a real token'}</td>"
        f"<td>{escape(case.note)}</td></tr>"
        for case in demo_cases()
    )
    mean_silver = ledger.mean_survival("silver_da")
    mean_oracle = ledger.mean_survival("oracle_da")
    mean_lead = ledger.mean_survival("lead2_da")
    mean_pivot = ledger.mean_survival("pivot_en")
    worst = ledger.worst()
    return f"""<!DOCTYPE html>
<html lang="da">
<head>
<meta charset="utf-8">
<title>Blåhøj Almanak — maalestok</title>
<style>
  :root {{
    --ink: #2b2118;
    --rule: #8a6a3a;
    --paper: #f4ead3;
    --card: #fff8e8;
    --ok: #2f6b3a;
    --scar: #9b2d1f;
    --muted: #6a5844;
  }}
  html {{ background: #d8c7a3; }}
  body {{
    margin: 0 auto;
    max-width: 920px;
    padding: 2rem 1.4rem 4rem;
    font-family: "Iowan Old Style", "Palatino Linotype", Palatino, serif;
    color: var(--ink);
    background: var(--paper);
    border-left: 12px solid #6b1d1d;
    border-right: 1px solid #cbb892;
  }}
  h1, h2, h3 {{ font-weight: 650; letter-spacing: 0.01em; }}
  h1 {{ font-size: 2rem; margin-bottom: 0.2rem; }}
  .deck {{ color: var(--muted); font-style: italic; margin-top: 0; }}
  nav a {{ color: var(--rule); margin-right: 0.8rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.92rem; }}
  th, td {{ border-bottom: 1px solid #e0d2b0; padding: 0.35rem 0.4rem; text-align: left; vertical-align: top; }}
  th {{ color: var(--muted); font-weight: 600; }}
  .ok {{ color: var(--ok); }}
  .scar {{ color: var(--scar); font-weight: 650; }}
  .card {{
    background: var(--card);
    border: 1px solid #e4d3aa;
    padding: 0.9rem 1rem;
    margin: 1.2rem 0;
  }}
  .bars {{ display: grid; gap: 0.35rem; margin: 1rem 0 1.4rem; }}
  .bar {{ display: grid; grid-template-columns: 8rem 1fr 4rem; gap: 0.5rem; align-items: center; }}
  .bar i {{ display: block; height: 0.7rem; background: #6b1d1d; }}
  code {{ font-family: "Source Code Pro", ui-monospace, monospace; font-size: 0.86em; }}
  .meta {{ color: var(--muted); font-size: 0.9rem; }}
</style>
</head>
<body>
<h1>Blåhøj Almanak</h1>
<p class="deck">A measuring-stick lab for the 2023 Danish→English→T5→Danish hops.
Parish: {escape(PARISH.name)}. Fiction only. No newspaper dump.</p>
<nav>
  <a href="#means">Means</a>
  <a href="#briefs">Briefs</a>
  <a href="#scar">NLLB scar</a>
</nav>
<h2 id="means">Hop survival on planted measures</h2>
<p>Share of source measures that land as <code>ok</code> after each hop.
Oracle is the hand-written faithful back-translation. Silver is the planted
2023-style summary. Lead-2 is the first two Danish sentences.</p>
<div class="bars">
  {_bar("pivot", mean_pivot)}
  {_bar("summary", ledger.mean_survival("summary_en"))}
  {_bar("silver", mean_silver)}
  {_bar("oracle", mean_oracle)}
  {_bar("lead-2", mean_lead)}
</div>
<p class="meta">Worst silver survival: <a href="#{escape(worst.article_id)}">{escape(worst.article_id)}</a>
({worst.survival("silver_da"):.0%}). Mean silver {mean_silver:.0%} vs oracle {mean_oracle:.0%}.</p>
<h2 id="briefs">Sixteen briefs</h2>
{''.join(rows)}
<h2 id="scar">NLLB prefixes on OPUS-MT</h2>
<p><code>translate.py</code> sets <code>target_prefixes = [[tgt_lang]]</code> with
NLLB codes and then decodes <code>hypotheses[0][1:]</code>. If the model does
not echo the prefix, the first real token is the one that disappears.</p>
<table>
  <tr><th>case</th><th>hypothesis</th><th>decoded</th><th>effect</th><th>note</th></tr>
  {scar_rows}
</table>
<p class="meta">Generated by <code>python3 -m maalestok report</code>. Original
ITU scripts on the repo root were not modified.</p>
</body>
</html>
"""


def _bar(label: str, value: float) -> str:
    width = max(0, min(100, round(value * 100)))
    return (
        f'<div class="bar"><span>{escape(label)}</span>'
        f'<i style="width:{width}%"></i><span>{value:.0%}</span></div>'
    )


def _article_section(article, entry) -> str:
    silver_pairs = entry.pairs["silver_da"]
    scars = [p for p in silver_pairs if p.label not in OK_LABELS and p.label != "hallucinated"]
    scar_html = "".join(_pair_row(p) for p in scars) or "<tr><td colspan=4>no classified scar</td></tr>"
    planted = "".join(
        f"<li><code>{escape(err.code)}</code>: {escape(err.source_raw)} → {escape(err.silver_raw)} "
        f"<span class='meta'>({escape(err.note)})</span></li>"
        for err in article.planted
    )
    return f"""
<section class="card" id="{escape(article.id)}">
  <h3>{escape(article.id)} — {escape(article.title)}</h3>
  <p class="meta">{escape(article.topic)} · source measures {entry.source_count} ·
  silver survival {entry.survival("silver_da"):.0%} ·
  oracle {entry.survival("oracle_da"):.0%} ·
  lead-2 {entry.survival("lead2_da"):.0%}</p>
  <p><strong>Danish source.</strong> {escape(article.body_da)}</p>
  <p><strong>Silver label.</strong> <span class="scar">{escape(article.silver_da)}</span></p>
  <p><strong>Oracle back-translation.</strong> {escape(article.oracle_da)}</p>
  <p><strong>Planted scars</strong></p>
  <ul>{planted}</ul>
  <table>
    <tr><th>label</th><th>source</th><th>silver</th><th>detail</th></tr>
    {scar_html}
  </table>
</section>
"""


def _pair_row(pair: HopPair) -> str:
    target = pair.target.raw if pair.target is not None else "—"
    return (
        f"<tr><td class='scar'>{escape(pair.label)}</td>"
        f"<td><code>{escape(pair.source.raw)}</code></td>"
        f"<td><code>{escape(target)}</code></td>"
        f"<td>{escape(pair.detail)}</td></tr>"
    )


def write_report(path: Path | None = None) -> Path:
    path = path or (REPORT_DIR / "index.html")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_html(), encoding="utf-8")
    return path
