"""Closed-world Danish↔English gloss for the Vesterklit gazette.

The 2023 pipeline used OPUS-MT (CTranslate2) both ways. This module does
not. It ships a hand-written word list that covers the gazette plus a
small function-word layer, then translates by looking up each token.

Two properties matter for the lab:

* Coverage is measurable. Every OOV token is recorded.
* The mapping is many-to-one and lossy. Round-tripping a sentence through
  DA→EN→DA is supposed to look worse than the gold parallel. That gap is
  the pedagogical stand-in for hop error in the neural pipeline.

Named entities that should stay unchanged (place names, people) live in
``IDENTITY``. Numbers and punctuation always pass through.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Sequence, Tuple

from .tokenize import tokenize_words

# Tokens that are the same in both languages in this closed world.
IDENTITY: Tuple[str, ...] = (
    "vesterklit",
    "havnepladsen",
    "klitsand",
    "nordmark",
    "mågeø",
    "mageo",
    "stenmole",
    "tangløb",
    "tanglob",
    "sølvdyp",
    "solvydp",
    "amberhus",
    "rylevej",
    "brohuset",
    "fjordpressen",
    "nordmark",
    "naturstyrelsen",
    "lisbeth",
    "holm",
    "karsten",
    "vang",
    "amina",
    "sørensen",
    "sorensen",
    "troels",
    "kjær",
    "kjaer",
    "ellen",
    "buhl",
    "mikkel",
    "ravn",
    "sofie",
    "tranberg",
    "poul",
    "nissen",
    "yasmin",
    "el-khatib",
    "henrik",
    "straarup",
    "nanna",
    "bus",
    "busser",
    "taxi",
    "museum",
    "digital",
    "arkiv",
    "archive",
    "quota",
)

# Danish token (lowercased, no trailing punct) -> English gloss.
# Keep entries single-token on the Danish side. Multi-word English glosses
# are allowed; the reverse map then only round-trips the first English word
# unless we also register a phrase. Prefer single-word glosses.
DA_EN: Dict[str, str] = {
    # function / closed class
    "i": "in",
    "en": "a",
    "et": "a",
    "og": "and",
    "eller": "or",
    "men": "but",
    "at": "to",
    "som": "that",
    "der": "there",
    "det": "it",
    "den": "the",
    "de": "the",
    "på": "on",
    "af": "of",
    "til": "to",
    "fra": "from",
    "med": "with",
    "for": "for",
    "om": "about",
    "ikke": "not",
    "kan": "can",
    "kunne": "could",
    "skal": "must",
    "skulle": "should",
    "vil": "will",
    "ville": "would",
    "er": "is",
    "var": "was",
    "blev": "became",
    "bliver": "becomes",
    "har": "has",
    "havde": "had",
    "være": "be",
    "være": "be",
    "få": "get",
    "får": "gets",
    "fik": "got",
    "gøre": "do",
    "gør": "does",
    "gjorde": "did",
    "sige": "say",
    "siger": "says",
    "sagde": "said",
    "åbne": "open",
    "åbner": "opens",
    "åbnede": "opened",
    "lukke": "close",
    "lukker": "closes",
    "efter": "after",
    "før": "before",
    "under": "under",
    "over": "over",
    "mellem": "between",
    "uden": "without",
    "mod": "against",
    "via": "via",
    "her": "here",
    "nu": "now",
    "senere": "later",
    "tidligere": "earlier",
    "allerede": "already",
    "stadig": "still",
    "også": "also",
    "kun": "only",
    "mere": "more",
    "flere": "several",
    "mange": "many",
    "alle": "all",
    "ingen": "no",
    "noget": "something",
    "nogle": "some",
    "denne": "this",
    "dette": "this",
    "disse": "these",
    "sin": "its",
    "sit": "its",
    "sine": "its",
    "hans": "his",
    "hendes": "her",
    "vores": "our",
    "deres": "their",
    "man": "one",
    "vi": "we",
    "jeg": "i",
    "hun": "she",
    "han": "he",
    "sig": "itself",
    "selv": "self",
    "så": "so",
    "hvis": "if",
    "når": "when",
    "hvor": "where",
    "hvordan": "how",
    "hvorfor": "why",
    "hvad": "what",
    "hvem": "who",
    "fordi": "because",
    "selvom": "although",
    "mens": "while",
    "samt": "plus",
    "både": "both",
    "enten": "either",
    "end": "than",
    "meget": "very",
    "helt": "fully",
    "næsten": "almost",
    "cirka": "about",
    "ca": "about",
    "ifølge": "according-to",
    "blandt": "among",
    "gennem": "through",
    "rundt": "around",
    "op": "up",
    "ned": "down",
    "ud": "out",
    "ind": "in",
    "igen": "again",
    "først": "first",
    "sidst": "last",
    "næste": "next",
    "nye": "new",
    "ny": "new",
    "nyt": "new",
    "gammel": "old",
    "gamle": "old",
    "stor": "large",
    "store": "large",
    "lille": "small",
    "små": "small",
    "lokal": "local",
    "lokale": "local",
    "offentlig": "public",
    "offentlige": "public",
    "midlertidig": "temporary",
    "midlertidigt": "temporarily",
    "mulig": "possible",
    "muligt": "possible",
    "sikker": "safe",
    "sikre": "secure",
    "klar": "ready",
    "klart": "ready",
    # news / municipal
    "stormen": "the-storm",
    "storm": "storm",
    "nat": "night",
    "nats": "night",
    "dag": "day",
    "dagen": "the-day",
    "morgen": "morning",
    "aften": "evening",
    "uge": "week",
    "ugen": "the-week",
    "måned": "month",
    "år": "year",
    "året": "the-year",
    "sommer": "summer",
    "sommeren": "the-summer",
    "efterår": "autumn",
    "efteråret": "the-autumn",
    "vinter": "winter",
    "forår": "spring",
    "færgeselskabet": "the-ferry-company",
    "færge": "ferry",
    "færgen": "the-ferry",
    "færger": "ferries",
    "afgang": "departure",
    "afgange": "departures",
    "aflyse": "cancel",
    "aflyste": "cancelled",
    "aflysning": "cancellation",
    "direktør": "director",
    "bølge": "wave",
    "bølgerne": "the-waves",
    "meter": "metres",
    "mandskabet": "the-crew",
    "fortøjningen": "the-mooring",
    "kommunen": "the-municipality",
    "kommune": "municipality",
    "kommunalbestyrelsen": "the-council",
    "byrådet": "the-town-council",
    "venteskur": "shelter",
    "kajen": "the-quay",
    "passagerer": "passengers",
    "kaffe": "coffee",
    "opdateringer": "updates",
    "hver": "each",
    "halve": "half",
    "time": "hour",
    "timer": "hours",
    "minutter": "minutes",
    "vurdering": "assessment",
    "sker": "happens",
    "klokken": "at",
    "kl": "at",
    "skoleelever": "schoolchildren",
    "elever": "pupils",
    "svømmestævne": "swim-meet",
    "kørt": "driven",
    "køre": "drive",
    "kører": "drives",
    "bus": "bus",
    "busser": "buses",
    "i": "in",
    "stedet": "instead",
    "vind": "wind",
    "vindmølle": "wind-turbine",
    "vindmøller": "wind-turbines",
    "testplads": "test-site",
    "mast": "mast",
    "master": "masts",
    "godkendt": "approved",
    "godkende": "approve",
    "godkendelse": "approval",
    "projekt": "project",
    "projektet": "the-project",
    "højde": "height",
    "høj": "tall",
    "naboer": "neighbours",
    "naboerne": "the-neighbours",
    "klage": "complaint",
    "klager": "complaints",
    "støj": "noise",
    "fugle": "birds",
    "trækfugle": "migratory-birds",
    "rapport": "report",
    "rapporten": "the-report",
    "miljø": "environment",
    "miljøvurdering": "environmental-review",
    "tag": "roof",
    "taget": "the-roof",
    "læk": "leak",
    "lækage": "leak",
    "regn": "rain",
    "regnen": "the-rain",
    "skole": "school",
    "skolen": "the-school",
    "klasser": "classes",
    "klasse": "class",
    "flyttet": "moved",
    "flytte": "move",
    "aulaen": "the-hall",
    "reparation": "repair",
    "reparationen": "the-repair",
    "håndværkere": "tradespeople",
    "uge": "week",
    "udgifter": "costs",
    "budget": "budget",
    "budgettet": "the-budget",
    "millioner": "million",
    "million": "million",
    "kroner": "kroner",
    "kr": "kr",
    "havn": "harbour",
    "havnen": "the-harbour",
    "udvidelse": "extension",
    "udvidelsen": "the-extension",
    "afstemning": "vote",
    "stemmer": "votes",
    "stemte": "voted",
    "for": "for",
    "imod": "against",
    "blanke": "blank",
    "kaj": "quay",
    "kajanlæg": "quay-works",
    "fiskere": "fishers",
    "fiskeriet": "the-fishery",
    "arbejde": "work",
    "arbejdspladser": "jobs",
    "turisme": "tourism",
    "turister": "tourists",
    "sommergæster": "summer-visitors",
    "udstilling": "exhibition",
    "udstillingen": "the-exhibition",
    "rav": "amber",
    "bronzealder": "bronze-age",
    "fund": "finds",
    "fundene": "the-finds",
    "gravhøj": "barrow",
    "omegnen": "the-area",
    "åbner": "opens",
    "lørdag": "saturday",
    "søndag": "sunday",
    "mandag": "monday",
    "tirsdag": "tuesday",
    "onsdag": "wednesday",
    "torsdag": "thursday",
    "fredag": "friday",
    "gratis": "free",
    "børn": "children",
    "voksne": "adults",
    "billet": "ticket",
    "billetter": "tickets",
    "natbus": "night-bus",
    "forsøg": "trial",
    "forsøget": "the-trial",
    "rute": "route",
    "ruten": "the-route",
    "stop": "stop",
    "stoppesteder": "stops",
    "weekenden": "the-weekend",
    "juni": "june",
    "juli": "july",
    "august": "august",
    "september": "september",
    "oktober": "october",
    "marts": "march",
    "april": "april",
    "maj": "may",
    "december": "december",
    "januar": "january",
    "februar": "february",
    "november": "november",
    "varmepumpe": "heat-pump",
    "varmepumper": "heat-pumps",
    "tilskud": "subsidy",
    "tilskuddet": "the-subsidy",
    "mursten": "brick",
    "huse": "houses",
    "husene": "the-houses",
    "ansøgning": "application",
    "ansøgninger": "applications",
    "frist": "deadline",
    "energimærke": "energy-label",
    "cykelsti": "bike-path",
    "cykelstien": "the-bike-path",
    "forsinket": "delayed",
    "forsinkelse": "delay",
    "klitter": "dunes",
    "klitten": "the-dune",
    "fredning": "conservation",
    "naturstyrelse": "nature-agency",
    "omlægning": "reroute",
    "bibliotek": "library",
    "biblioteket": "the-library",
    "sogne": "parish",
    "sogn": "parish",
    "kirkebøger": "parish-registers",
    "kirkebøgerne": "the-parish-registers",
    "scannet": "scanned",
    "scannes": "are-scanned",
    "frivillige": "volunteers",
    "læsestue": "reading-room",
    "slægtsforskere": "genealogists",
    "fiskeriforeningen": "the-fishery-association",
    "kvote": "quota",
    "kvoten": "the-quota",
    "møde": "meeting",
    "mødet": "the-meeting",
    "ton": "tonnes",
    "torsk": "cod",
    "rødspætte": "plaice",
    "fangst": "catch",
    "sæson": "season",
    "sæsonen": "the-season",
    "medlemmer": "members",
    "aftale": "agreement",
    "aftalen": "the-agreement",
    "ministeriet": "the-ministry",
    "brev": "letter",
    "peger": "points",
    "lavere": "lower",
    "højere": "higher",
    "tal": "figures",
    "tallet": "the-figure",
    "procent": "percent",
    "pct": "pct",
    "bestyrelsen": "the-board",
    "formand": "chair",
    "formanden": "the-chair",
    "næstformand": "vice-chair",
    "teknisk": "technical",
    "forvaltning": "department",
    "forvaltningen": "the-department",
    "ingeniør": "engineer",
    "læge": "doctor",
    "lærer": "teacher",
    "lærere": "teachers",
    "borgmester": "mayor",
    "borgmesteren": "the-mayor",
    "presse": "press",
    "avis": "newspaper",
    "avisen": "the-newspaper",
    "artikel": "article",
    "artiklen": "the-article",
    "by": "town",
    "byen": "the-town",
    "ø": "island",
    "øen": "the-island",
    "kyst": "coast",
    "kysten": "the-coast",
    "vand": "water",
    "vandet": "the-water",
    "sand": "sand",
    "vind": "wind",
    "vejr": "weather",
    "vejret": "the-weather",
    "advarsel": "warning",
    "advarslen": "the-warning",
    "beredskab": "emergency-service",
    "politi": "police",
    "politiet": "the-police",
    "brand": "fire",
    "hospital": "hospital",
    "patienter": "patients",
    "vej": "road",
    "vejen": "the-road",
    "bro": "bridge",
    "broen": "the-bridge",
    "sti": "path",
    "stien": "the-path",
    "anlæg": "works",
    "anlægsarbejde": "construction",
    "entreprenør": "contractor",
    "entreprenøren": "the-contractor",
    "kontrakt": "contract",
    "kontrakten": "the-contract",
    "forsinket": "delayed",
    "plan": "plan",
    "planen": "the-plan",
    "forslag": "proposal",
    "forslaget": "the-proposal",
    "høring": "hearing",
    "høringen": "the-hearing",
    "borger": "resident",
    "borgere": "residents",
    "borgerne": "the-residents",
    "indbyggere": "inhabitants",
    "familie": "family",
    "familier": "families",
    "husstand": "household",
    "husstande": "households",
    "ansøger": "applicant",
    "ansøgere": "applicants",
    "bevilling": "grant",
    "bevillinger": "grants",
    "økonomi": "finances",
    "udgift": "expense",
    "indtægt": "income",
    "skat": "tax",
    "skatten": "the-tax",
    "afgift": "fee",
    "prisen": "the-price",
    "pris": "price",
    "billigere": "cheaper",
    "dyrere": "dearer",
    "gratis": "free",
    "åben": "open",
    "lukket": "closed",
    "åbningstid": "opening-hour",
    "åbningstider": "opening-hours",
    "lørdag": "saturday",
    "søndag": "sunday",
    "natten": "the-night",
    "i": "in",
    "nat": "night",
    "i": "in",
    "går": "yesterday",
    "igår": "yesterday",
    "imorges": "this-morning",
    "iamorges": "this-morning",
    "foreløbig": "for-now",
    "endelig": "final",
    "endeligt": "finally",
    "foreløbige": "preliminary",
    "officielt": "officially",
    "officiel": "official",
    "skriftligt": "in-writing",
    "mundtligt": "orally",
    "møde": "meeting",
    "samling": "session",
    "punkt": "item",
    "dagsorden": "agenda",
    "beslutning": "decision",
    "beslutningen": "the-decision",
    "vedtog": "adopted",
    "vedtage": "adopt",
    "forkastede": "rejected",
    "udsætte": "postpone",
    "udsat": "postponed",
    "behov": "need",
    "nødvendigt": "necessary",
    "vigtigt": "important",
    "alvorligt": "serious",
    "alvorlig": "serious",
    "farligt": "dangerous",
    "farlig": "dangerous",
    "sikkert": "safely",
    "usikkert": "uncertain",
    "klart": "clear",
    "uklart": "unclear",
    "enig": "agreed",
    "enige": "agreed",
    "uenige": "disagreed",
    "bekymret": "worried",
    "bekymrede": "worried",
    "glad": "glad",
    "tilfreds": "satisfied",
    "skuffet": "disappointed",
    "pegede": "pointed",
    "understregede": "stressed",
    "oplyste": "stated",
    "fortalte": "told",
    "forklarede": "explained",
    "bekræftede": "confirmed",
    "afviste": "denied",
    "lovede": "promised",
    "krævede": "demanded",
    "bad": "asked",
    "spurgte": "asked",
    "svarede": "answered",
    "skrev": "wrote",
    "læste": "read",
    "viste": "showed",
    "fandt": "found",
    "søgte": "sought",
    "ventede": "waited",
    "begyndte": "began",
    "sluttede": "ended",
    "fortsætter": "continues",
    "fortsatte": "continued",
    "stopper": "stops",
    "stoppede": "stopped",
    "starter": "starts",
    "startede": "started",
    "åbnes": "is-opened",
    "lukkes": "is-closed",
    "bygges": "is-built",
    "bygge": "build",
    "bygger": "builds",
    "byggede": "built",
    "anlægge": "construct",
    "anlægger": "constructs",
    "regner": "rains",
    "regnede": "rained",
    "blæser": "blows",
    "blæste": "blew",
    "målt": "measured",
    "målte": "measured",
    "måle": "measure",
    "talte": "counted",
    "tælle": "count",
    "tæller": "counts",
    "viser": "shows",
    "betyder": "means",
    "gælder": "applies",
    "gældende": "current",
    "sammen": "together",
    "alene": "alone",
    "fælles": "shared",
    "egen": "own",
    "eget": "own",
    "egne": "own",
    "første": "first",
    "anden": "second",
    "tredje": "third",
    "sidste": "last",
    "kommende": "upcoming",
    "seneste": "latest",
    "tidlig": "early",
    "tidligt": "early",
    "sent": "late",
    "sen": "late",
    "lang": "long",
    "lange": "long",
    "kort": "short",
    "korte": "short",
    "bred": "wide",
    "smal": "narrow",
    "dyb": "deep",
    "dybe": "deep",
    "høje": "tall",
    "lav": "low",
    "lave": "low",
    "våd": "wet",
    "våde": "wet",
    "tør": "dry",
    "tørre": "dry",
    "kold": "cold",
    "kolde": "cold",
    "varm": "warm",
    "varme": "warm",
    "mørk": "dark",
    "lys": "light",
    "rød": "red",
    "gul": "yellow",
    "grøn": "green",
    "blå": "blue",
    "sort": "black",
    "hvid": "white",
    "tre": "three",
    "fire": "four",
    "fem": "five",
    "seks": "six",
    "syv": "seven",
    "otte": "eight",
    "ni": "nine",
    "ti": "ten",
    "tolv": "twelve",
    "tyve": "twenty",
    "tredive": "thirty",
    "halvtreds": "fifty",
    "hundrede": "hundred",
    "tusind": "thousand",
    "tusinde": "thousand",
    "to": "two",
    "ét": "one",
    "én": "one",
    "begge": "both",
    "ingen": "nobody",
    "alle": "everyone",
    "meget": "much",
    "lidt": "little",
    "nok": "enough",
    "for": "too",
    "alt": "everything",
    "intet": "nothing",
    "samme": "same",
    "anden": "other",
    "andre": "other",
    "sådan": "such",
    "sådanne": "such",
    "hele": "whole",
    "halv": "half",
    "halvdelen": "the-half",
    "del": "part",
    "delen": "the-part",
    "dele": "parts",
    "gang": "time",
    "gange": "times",
    "sted": "place",
    "steder": "places",
    "stedet": "the-place",
    "gang": "occasion",
    "vej": "way",
    "måde": "way",
    "mulighed": "option",
    "muligheder": "options",
    "problem": "problem",
    "problemet": "the-problem",
    "løsning": "solution",
    "løsningen": "the-solution",
    "årsag": "cause",
    "årsagen": "the-cause",
    "følge": "consequence",
    "følger": "consequences",
    "risiko": "risk",
    "risikoen": "the-risk",
    "sikkerhed": "safety",
    "sikkerheden": "the-safety",
    "ansvar": "responsibility",
    "ansvaret": "the-responsibility",
    "krav": "requirement",
    "kravene": "the-requirements",
    "regel": "rule",
    "regler": "rules",
    "lov": "law",
    "loven": "the-law",
    "tilladelse": "permit",
    "tilladelsen": "the-permit",
    "forbud": "ban",
    "forbuddet": "the-ban",
    # residual gazette types (closed-world, not a general dictionary)
    "ad": "along",
    "aflyst": "cancelled",
    "aldrig": "never",
    "anlægsarbejdet": "the-construction",
    "ansøgningen": "the-application",
    "arkivet": "the-archive",
    "begynder": "begins",
    "beredskabet": "the-emergency-service",
    "betaler": "pays",
    "betinget": "conditional",
    "bibliotekets": "the-library's",
    "billeder": "pictures",
    "bind": "volumes",
    "blank": "blank",
    "bredere": "wider",
    "brevet": "the-letter",
    "bronzealderfund": "bronze-age-finds",
    "busserne": "the-buses",
    "bådene": "the-boats",
    "båndoptager": "tape-recorder",
    "chef": "lead",
    "cykler": "cycle",
    "dansk": "danish",
    "dem": "them",
    "derefter": "afterwards",
    "derfor": "therefore",
    "digitalt": "digitally",
    "efterårsregnen": "the-autumn-rain",
    "ekstra": "extra",
    "ellers": "otherwise",
    "energimærket": "the-energy-label",
    "engelsk": "english",
    "falder": "falls",
    "fanger": "catches",
    "fiske": "fish",
    "flyttede": "moved",
    "flytter": "moves",
    "forrang": "priority",
    "forældre": "parents",
    "fristen": "the-deadline",
    "fugletællingen": "the-bird-count",
    "fysiske": "physical",
    "færdig": "finished",
    "færre": "fewer",
    "givet": "given",
    "glemmer": "forget",
    "gravhøje": "barrows",
    "gravhøjene": "the-barrows",
    "grund": "reason",
    "gulvet": "the-floor",
    "gymnastik": "gymnastics",
    "gået": "walked",
    "havnens": "the-harbour's",
    "hemmelig": "secret",
    "hjemmesiden": "the-website",
    "holde": "keep",
    "holder": "stays",
    "holdt": "held",
    "hårdere": "harder",
    "inde": "inland",
    "inden": "before",
    "indtil": "until",
    "kabler": "cables",
    "kajplads": "quay-space",
    "klagerne": "the-complaints",
    "kom": "came",
    "kommer": "comes",
    "koordinater": "coordinates",
    "koster": "costs",
    "kræver": "requires",
    "kystkile": "coastal-wedge",
    "købe": "buy",
    "lagt": "put",
    "langs": "along",
    "levende": "living",
    "ligger": "sits",
    "linje": "line",
    "lås": "lock",
    "lægger": "puts",
    "længere": "further",
    "læse": "read",
    "læsesalen": "the-reading-room",
    "masten": "the-mast",
    "medlemmerne": "the-members",
    "miljøvurderingen": "the-environmental-review",
    "mindst": "at-least",
    "museets": "the-museum's",
    "målepunkt": "measuring-point",
    "møllepark": "turbine-park",
    "mørke": "dark",
    "navne": "names",
    "nej": "no",
    "nogen": "anyone",
    "offentligt": "publicly",
    "omkring": "around",
    "partier": "stretches",
    "pege": "point",
    "penge": "money",
    "personer": "people",
    "pr": "per",
    "presset": "tight",
    "præcise": "precise",
    "prøver": "tries",
    "redepladser": "nesting-sites",
    "restbeløbet": "the-remainder",
    "runde": "round",
    "sad": "sat",
    "scanner": "scans",
    "sendt": "sent",
    "side": "page",
    "siden": "since",
    "sider": "pages",
    "skaber": "creates",
    "skemaet": "the-form",
    "skoleeleverne": "the-schoolchildren",
    "skrevet": "written",
    "skriver": "writes",
    "skønner": "estimates",
    "slutter": "closes",
    "smalle": "narrow",
    "stående": "standing",
    "sælges": "are-sold",
    "sæsoner": "seasons",
    "tage": "take",
    "tager": "takes",
    "tages": "are-taken",
    "taler": "talks",
    "tallene": "the-figures",
    "teksterne": "the-texts",
    "testmast": "test-mast",
    "tilbage": "back",
    "træk": "row",
    "tur": "trip",
    "tvang": "forced",
    "udsatte": "postponed",
    "udvalg": "selection",
    "uger": "weeks",
    "varer": "lasts",
    "ved": "at",
    "vedlægge": "attach",
    "ventet": "expected",
    "vilkår": "conditions",
    "vinden": "the-wind",
    "vist": "shown",
    "vådt": "wet",
    "væk": "away",
    "været": "been",
    "weekender": "weekends",
    "åbnet": "opened",
    "årstal": "years",
    "ældre": "older",
    "ældste": "oldest",
    "én": "one",
    "ét": "one",
}

# Extra identity-ish tokens registered as DA->same EN.
for _name in IDENTITY:
    key = _name.strip().lower()
    if key and key not in DA_EN:
        DA_EN[key] = key


@dataclass
class GlossResult:
    text: str
    unknown: List[str] = field(default_factory=list)
    n_tokens: int = 0
    n_glossed: int = 0

    @property
    def coverage(self) -> float:
        if self.n_tokens == 0:
            return 1.0
        return self.n_glossed / self.n_tokens


def _apply_case(src: str, dst: str) -> str:
    if not src or not dst:
        return dst
    if src.isupper():
        return dst.upper()
    if src[0].isupper():
        return dst[0].upper() + dst[1:]
    return dst


def reverse_lexicon(forward: Dict[str, str] | None = None) -> Dict[str, str]:
    """Build EN→DA. First Danish spelling wins if several map to one gloss."""
    src = forward if forward is not None else DA_EN
    rev: Dict[str, str] = {}
    for da, en in src.items():
        key = en.lower()
        if key not in rev:
            rev[key] = da
    return rev


_REVERSE: Dict[str, str] | None = None


def english_to_danish_lexicon() -> Dict[str, str]:
    global _REVERSE
    if _REVERSE is None:
        _REVERSE = reverse_lexicon()
    return _REVERSE


def gloss_tokens(
    tokens: Sequence[str],
    table: Dict[str, str],
) -> Tuple[List[str], List[str], int, int]:
    out: List[str] = []
    unknown: List[str] = []
    n_content = 0
    n_glossed = 0
    for tok in tokens:
        if not tok:
            continue
        if not tok[0].isalnum():
            out.append(tok)
            continue
        n_content += 1
        key = tok.lower()
        if key.isdigit() or any(ch.isdigit() for ch in key):
            out.append(tok)
            n_glossed += 1
            continue
        hit = table.get(key)
        if hit is None:
            out.append(tok)
            unknown.append(tok)
        else:
            out.append(_apply_case(tok, hit))
            n_glossed += 1
    return out, unknown, n_content, n_glossed


def gloss_danish_to_english(text: str) -> GlossResult:
    tokens = tokenize_words(text)
    out, unknown, n_content, n_glossed = gloss_tokens(tokens, DA_EN)
    return GlossResult(
        text=_join_readable(out),
        unknown=unknown,
        n_tokens=n_content,
        n_glossed=n_glossed,
    )


def gloss_english_to_danish(text: str) -> GlossResult:
    tokens = tokenize_words(text)
    out, unknown, n_content, n_glossed = gloss_tokens(tokens, english_to_danish_lexicon())
    return GlossResult(
        text=_join_readable(out),
        unknown=unknown,
        n_tokens=n_content,
        n_glossed=n_glossed,
    )


def _join_readable(tokens: Iterable[str]) -> str:
    """Join tokens with spaces, then tuck punctuation against the left word.

    Unlike ``packing.join_tokens`` this is for *display* of gloss hops, not
    for reproducing the 2023 ``' '.join`` scar.
    """
    parts: List[str] = []
    for tok in tokens:
        if not tok:
            continue
        if parts and tok in {".", ",", ";", ":", "!", "?", ")", "»"}:
            parts[-1] = parts[-1] + tok
        elif tok in {"(", "«"}:
            parts.append(tok)
        else:
            if parts and parts[-1] in {"(", "«"}:
                parts[-1] = parts[-1] + tok
            else:
                parts.append(tok)
    return " ".join(parts)


def coverage_report(texts: Sequence[str], danish: bool = True) -> Dict[str, float | int]:
    unknown: List[str] = []
    n_tokens = 0
    n_glossed = 0
    fn = gloss_danish_to_english if danish else gloss_english_to_danish
    for text in texts:
        result = fn(text)
        unknown.extend(result.unknown)
        n_tokens += result.n_tokens
        n_glossed += result.n_glossed
    uniq = sorted(set(u.lower() for u in unknown))
    return {
        "n_tokens": n_tokens,
        "n_glossed": n_glossed,
        "coverage": (n_glossed / n_tokens) if n_tokens else 1.0,
        "n_unknown_types": len(uniq),
        "unknown_types": uniq,
    }
